version: '3.7'
services:
  bright-api-service:
    image: m1ky91/bright-api
    ports:
      - 8081:8080
    depends_on:
      - bright-api-database
    networks:
      bright-api-network:
        aliases:
          - bright-api-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bright-api-database/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
  bright-api-database:
    image: mysql:8.0.14
    networks:
      bright-api-network:
        aliases:
          - bright-api-database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ONETIME_PASSWORD=true
networks:
  bright-api-network: