spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brightdb
    username: root
    password: password
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
initialize: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:hsqldb:mem:brightdb;DB_CLOSE_DELAY=-1
    username: root
    password: password